### PR TITLE
Atlantis Test Pull Request

### PR DESCRIPTION
**Pull request by YoonDongGwan**

### CODE REVIEW

**Comment by YoonDongGwan** [comment]
Ran Plan for dir: `aws` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.ec2_atlantis.aws_instance.ec2_instance must be replaced
-/+ resource "aws_instance" "ec2_instance" {
      ~ arn                                  = "arn:aws:ec2:ap-northeast-2:xxxxxxxxxx:instance/i-032238b4c2f67a644" -> (known after apply)
      ~ associate_public_ip_address          = true -> (known after apply)
      ~ availability_zone                    = "ap-northeast-2a" -> (known after apply)
      ~ cpu_core_count                       = 1 -> (known after apply)
      ~ cpu_threads_per_core                 = 2 -> (known after apply)
      ~ disable_api_stop                     = false -> (known after apply)
      ~ disable_api_termination              = false -> (known after apply)
      ~ ebs_optimized                        = false -> (known after apply)
      - hibernation                          = false -> null
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      ~ id                                   = "i-032238b4c2f67a644" -> (known after apply)
      ~ instance_initiated_shutdown_behavior = "stop" -> (known after apply)
      + instance_lifecycle                   = (known after apply)
      ~ instance_state                       = "running" -> (known after apply)
      ~ ipv6_address_count                   = 0 -> (known after apply)
      ~ ipv6_addresses                       = [] -> (known after apply)
      ~ key_name                             = "terraform-20241219080943026000000001" -> (known after apply) # forces replacement
      ~ monitoring                           = false -> (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      ~ placement_partition_number           = 0 -> (known after apply)
      ~ primary_network_interface_id         = "eni-0c0f89f50f4140dc0" -> (known after apply)
      ~ private_dns                          = "ip-10-100-0-215.ap-northeast-2.compute.internal" -> (known after apply)
      ~ private_ip                           = "10.100.0.215" -> (known after apply)
      ~ public_dns                           = "ec2-3-35-231-83.ap-northeast-2.compute.amazonaws.com" -> (known after apply)
      ~ public_ip                            = "3.35.231.83" -> (known after apply)
      ~ secondary_private_ips                = [] -> (known after apply)
      ~ security_groups                      = [] -> (known after apply)
      + spot_instance_request_id             = (known after apply)
        tags                                 = {
            "Name" = "ec2-ap-northeast-2a-atlantis"
        }
      ~ tenancy                              = "default" -> (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
        # (8 unchanged attributes hidden)

      ~ capacity_reservation_specification (known after apply)
      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      ~ cpu_options (known after apply)
      - cpu_options {
          - core_count       = 1 -> null
          - threads_per_core = 2 -> null
            # (1 unchanged attribute hidden)
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      ~ ebs_block_device (known after apply)

      ~ enclave_options (known after apply)
      - enclave_options {
          - enabled = false -> null
        }

      ~ ephemeral_block_device (known after apply)

      ~ instance_market_options (known after apply)

      ~ maintenance_options (known after apply)
      - maintenance_options {
          - auto_recovery = "default" -> null
        }

      ~ metadata_options (known after apply)
      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_protocol_ipv6          = "disabled" -> null
          - http_put_response_hop_limit = 2 -> null
          - http_tokens                 = "required" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      ~ network_interface (known after apply)

      ~ private_dns_name_options (known after apply)
      - private_dns_name_options {
          - enable_resource_name_dns_a_record    = false -> null
          - enable_resource_name_dns_aaaa_record = false -> null
          - hostname_type                        = "ip-name" -> null
        }

      ~ root_block_device (known after apply)
      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/xvda" -> null
          - encrypted             = false -> null
          - iops                  = 3000 -> null
          - tags                  = {} -> null
          - tags_all              = {} -> null
          - throughput            = 125 -> null
          - volume_id             = "vol-0b1677c1b98156cbc" -> null
          - volume_size           = 30 -> null
          - volume_type           = "gp3" -> null
            # (1 unchanged attribute hidden)
        }
    }

  # module.ec2_atlantis.aws_key_pair.ec2_key_pair must be replaced
-/+ resource "aws_key_pair" "ec2_key_pair" {
      ~ arn             = "arn:aws:ec2:ap-northeast-2:xxxxxxxxxx:key-pair/terraform-20241219080943026000000001" -> (known after apply)
      ~ fingerprint     = "7f:a8:0c:d5:f2:21:58:df:ab:1b:28:56:7c:3c:50:37" -> (known after apply)
      ~ id              = "terraform-20241219080943026000000001" -> (known after apply)
      ~ key_name        = "terraform-20241219080943026000000001" -> (known after apply)
      ~ key_name_prefix = "terraform-" -> (known after apply)
      ~ key_pair_id     = "key-01723d22e29df9ece" -> (known after apply)
      ~ key_type        = "rsa" -> (known after apply)
      - public_key      = "ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" -> null # forces replacement
      - tags            = {} -> null
      ~ tags_all        = {} -> (known after apply)
    }

  # module.ec2_bastion.aws_instance.ec2_instance will be created
+ resource "aws_instance" "ec2_instance" {
      + ami                                  = "ami-043f11a3cf733c42d"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_lifecycle                   = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t2.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + spot_instance_request_id             = (known after apply)
      + subnet_id                            = "subnet-04cc7ac81d06fe2c7"
      + tags                                 = {
          + "Name" = "ec2-ap-northeast-2a-bastion"
        }
      + tags_all                             = {
          + "Name" = "ec2-ap-northeast-2a-bastion"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification (known after apply)

      + cpu_options (known after apply)

      + ebs_block_device (known after apply)

      + enclave_options (known after apply)

      + ephemeral_block_device (known after apply)

      + instance_market_options (known after apply)

      + maintenance_options (known after apply)

      + metadata_options (known after apply)

      + network_interface (known after apply)

      + private_dns_name_options (known after apply)

      + root_block_device (known after apply)
    }

  # module.ec2_bastion.aws_key_pair.ec2_key_pair will be created
+ resource "aws_key_pair" "ec2_key_pair" {
      + arn             = (known after apply)
      + fingerprint     = (known after apply)
      + id              = (known after apply)
      + key_name        = (known after apply)
      + key_name_prefix = (known after apply)
      + key_pair_id     = (known after apply)
      + key_type        = (known after apply)
      + tags_all        = (known after apply)
        # (1 unchanged attribute hidden)
    }

  # module.ec2_bastion.aws_security_group.ec2_security_group will be created
+ resource "aws_security_group" "ec2_security_group" {
      + arn                    = (known after apply)
      + description            = "Managed by Terraform"
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "sgr-ec2-ap-northeast-2a-bastion"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags_all               = (known after apply)
      + vpc_id                 = "vpc-0570e90b16e81586c"
    }

  # module.ec2_bastion.aws_vpc_security_group_egress_rule.allow_all will be created
+ resource "aws_vpc_security_group_egress_rule" "allow_all" {
      + arn                    = (known after apply)
      + cidr_ipv4              = "0.0.0.0/0"
      + id                     = (known after apply)
      + ip_protocol            = "-1"
      + security_group_id      = (known after apply)
      + security_group_rule_id = (known after apply)
      + tags_all               = {}
    }

  # module.ec2_bastion.aws_vpc_security_group_ingress_rule.allow_9080 will be created
+ resource "aws_vpc_security_group_ingress_rule" "allow_9080" {
      + arn                    = (known after apply)
      + cidr_ipv4              = "0.0.0.0/0"
      + from_port              = 9080
      + id                     = (known after apply)
      + ip_protocol            = "tcp"
      + security_group_id      = (known after apply)
      + security_group_rule_id = (known after apply)
      + tags_all               = {}
      + to_port                = 9080
    }

  # module.ec2_bastion.aws_vpc_security_group_ingress_rule.allow_ssh will be created
+ resource "aws_vpc_security_group_ingress_rule" "allow_ssh" {
      + arn                    = (known after apply)
      + cidr_ipv4              = "0.0.0.0/0"
      + from_port              = 22
      + id                     = (known after apply)
      + ip_protocol            = "tcp"
      + security_group_id      = (known after apply)
      + security_group_rule_id = (known after apply)
      + tags_all               = {}
      + to_port                = 22
    }

Plan: 8 to add, 0 to change, 2 to destroy.

Changes to Outputs:
~ ec2_atlantis_ip = "3.35.231.83" -> (known after apply)
```
</details>

* :arrow_forward: To **apply** this plan, comment:
  ```shell
  atlantis apply -d aws
  ```
* :put_litter_in_its_place: To **delete** this plan and lock, click [here](http://a6728050edc3:4141/lock?id=YoonDongGwan%252Fterraform-demo%252Faws%252Fdefault)
* :repeat: To **plan** this project again, comment:
  ```shell
  atlantis plan -d aws
  ```
Plan: 8 to add, 0 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this Pull Request, comment:
  ```shell
  atlantis apply
  ```
* :put_litter_in_its_place: To **delete** all plans and locks from this Pull Request, comment:
  ```shell
  atlantis unlock
  ```

**Comment by YoonDongGwan** [comment]
atlantis unlock

**Comment by YoonDongGwan** [comment]
All Atlantis locks for this PR have been unlocked and plans discarded

**Comment by YoonDongGwan** [comment]
atlantis plan

**Comment by ddock-develop** [comment]
Ran Plan for dir: `aws` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running 'sh -c' '/usr/local/bin/terraform init -input=false' in '/home/atlantis/.atlantis/repos/YoonDongGwan/terraform-demo/3/default/aws': exit status 1
Initializing the backend...
Initializing modules...
- ec2_atlantis in modules/ec2
- ec2_bastion in modules/ec2
- private_subnet in modules/subnet
- public_subnet in modules/subnet
- s3_tfstate in modules/s3
- vpc in modules/vpc
╷
│ Error: No valid credential sources found
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: failed to refresh cached credentials, no EC2 IMDS role found,
│ operation error ec2imds: GetMetadata, http response error StatusCode: 404,
│ request to EC2 IMDS failed
│ 
╵

```
</details>

**Comment by YoonDongGwan** [comment]
atlantis plan

**Comment by YoonDongGwan** [comment]
atlantis plan

**Comment by YoonDongGwan** [comment]
Ran Plan for dir: `aws` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.ec2_atlantis.aws_instance.ec2_instance must be replaced
-/+ resource "aws_instance" "ec2_instance" {
      ~ arn                                  = "arn:aws:ec2:ap-northeast-2:XXXXXXXXX:instance/i-032238b4c2f67a644" -> (known after apply)
      ~ associate_public_ip_address          = true -> (known after apply)
      ~ availability_zone                    = "ap-northeast-2a" -> (known after apply)
      ~ cpu_core_count                       = 1 -> (known after apply)
      ~ cpu_threads_per_core                 = 2 -> (known after apply)
      ~ disable_api_stop                     = false -> (known after apply)
      ~ disable_api_termination              = false -> (known after apply)
      ~ ebs_optimized                        = false -> (known after apply)
      - hibernation                          = false -> null
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      ~ id                                   = "i-032238b4c2f67a644" -> (known after apply)
      ~ instance_initiated_shutdown_behavior = "stop" -> (known after apply)
      + instance_lifecycle                   = (known after apply)
      ~ instance_state                       = "running" -> (known after apply)
      ~ ipv6_address_count                   = 0 -> (known after apply)
      ~ ipv6_addresses                       = [] -> (known after apply)
      ~ key_name                             = "terraform-20241219080943026000000001" -> (known after apply) # forces replacement
      ~ monitoring                           = false -> (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      ~ placement_partition_number           = 0 -> (known after apply)
      ~ primary_network_interface_id         = "eni-0c0f89f50f4140dc0" -> (known after apply)
      ~ private_dns                          = "ip-10-100-0-215.ap-northeast-2.compute.internal" -> (known after apply)
      ~ private_ip                           = "10.100.0.215" -> (known after apply)
      ~ public_dns                           = "ec2-3-35-231-83.ap-northeast-2.compute.amazonaws.com" -> (known after apply)
      ~ public_ip                            = "3.35.231.83" -> (known after apply)
      ~ secondary_private_ips                = [] -> (known after apply)
      ~ security_groups                      = [] -> (known after apply)
      + spot_instance_request_id             = (known after apply)
        tags                                 = {
            "Name" = "ec2-ap-northeast-2a-atlantis"
        }
      ~ tenancy                              = "default" -> (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
        # (8 unchanged attributes hidden)

      ~ capacity_reservation_specification (known after apply)
      - capacity_reservation_specification {
          - capacity_reservation_preference = "open" -> null
        }

      ~ cpu_options (known after apply)
      - cpu_options {
          - core_count       = 1 -> null
          - threads_per_core = 2 -> null
            # (1 unchanged attribute hidden)
        }

      - credit_specification {
          - cpu_credits = "unlimited" -> null
        }

      ~ ebs_block_device (known after apply)

      ~ enclave_options (known after apply)
      - enclave_options {
          - enabled = false -> null
        }

      ~ ephemeral_block_device (known after apply)

      ~ instance_market_options (known after apply)

      ~ maintenance_options (known after apply)
      - maintenance_options {
          - auto_recovery = "default" -> null
        }

      ~ metadata_options (known after apply)
      - metadata_options {
          - http_endpoint               = "enabled" -> null
          - http_protocol_ipv6          = "disabled" -> null
          - http_put_response_hop_limit = 2 -> null
          - http_tokens                 = "required" -> null
          - instance_metadata_tags      = "disabled" -> null
        }

      ~ network_interface (known after apply)

      ~ private_dns_name_options (known after apply)
      - private_dns_name_options {
          - enable_resource_name_dns_a_record    = false -> null
          - enable_resource_name_dns_aaaa_record = false -> null
          - hostname_type                        = "ip-name" -> null
        }

      ~ root_block_device (known after apply)
      - root_block_device {
          - delete_on_termination = true -> null
          - device_name           = "/dev/xvda" -> null
          - encrypted             = false -> null
          - iops                  = 3000 -> null
          - tags                  = {} -> null
          - tags_all              = {} -> null
          - throughput            = 125 -> null
          - volume_id             = "vol-0b1677c1b98156cbc" -> null
          - volume_size           = 30 -> null
          - volume_type           = "gp3" -> null
            # (1 unchanged attribute hidden)
        }
    }

  # module.ec2_atlantis.aws_key_pair.ec2_key_pair must be replaced
-/+ resource "aws_key_pair" "ec2_key_pair" {
      ~ arn             = "arn:aws:ec2:ap-northeast-2:XXXXXXXXX:key-pair/terraform-20241219080943026000000001" -> (known after apply)
      ~ fingerprint     = "7f:a8:0c:d5:f2:21:58:df:ab:1b:28:56:7c:3c:50:37" -> (known after apply)
      ~ id              = "terraform-20241219080943026000000001" -> (known after apply)
      ~ key_name        = "terraform-20241219080943026000000001" -> (known after apply)
      ~ key_name_prefix = "terraform-" -> (known after apply)
      ~ key_pair_id     = "key-01723d22e29df9ece" -> (known after apply)
      ~ key_type        = "rsa" -> (known after apply)
      - public_key      = "ssh-rsa XXXXXXXXXXXX" -> null # forces replacement
      - tags            = {} -> null
      ~ tags_all        = {} -> (known after apply)
    }

  # module.ec2_bastion.aws_instance.ec2_instance will be created
+ resource "aws_instance" "ec2_instance" {
      + ami                                  = "ami-043f11a3cf733c42d"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_stop                     = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_lifecycle                   = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "t2.micro"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + spot_instance_request_id             = (known after apply)
      + subnet_id                            = "subnet-04cc7ac81d06fe2c7"
      + tags                                 = {
          + "Name" = "ec2-ap-northeast-2a-bastion"
        }
      + tags_all                             = {
          + "Name" = "ec2-ap-northeast-2a-bastion"
        }
      + tenancy                              = (known after apply)
      + user_data                            = (known after apply)
      + user_data_base64                     = (known after apply)
      + user_data_replace_on_change          = false
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification (known after apply)

      + cpu_options (known after apply)

      + ebs_block_device (known after apply)

      + enclave_options (known after apply)

      + ephemeral_block_device (known after apply)

      + instance_market_options (known after apply)

      + maintenance_options (known after apply)

      + metadata_options (known after apply)

      + network_interface (known after apply)

      + private_dns_name_options (known after apply)

      + root_block_device (known after apply)
    }

  # module.ec2_bastion.aws_key_pair.ec2_key_pair will be created
+ resource "aws_key_pair" "ec2_key_pair" {
      + arn             = (known after apply)
      + fingerprint     = (known after apply)
      + id              = (known after apply)
      + key_name        = (known after apply)
      + key_name_prefix = (known after apply)
      + key_pair_id     = (known after apply)
      + key_type        = (known after apply)
      + tags_all        = (known after apply)
        # (1 unchanged attribute hidden)
    }

  # module.ec2_bastion.aws_security_group.ec2_security_group will be created
+ resource "aws_security_group" "ec2_security_group" {
      + arn                    = (known after apply)
      + description            = "Managed by Terraform"
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "sgr-ec2-ap-northeast-2a-bastion"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags_all               = (known after apply)
      + vpc_id                 = "vpc-0570e90b16e81586c"
    }

  # module.ec2_bastion.aws_vpc_security_group_egress_rule.allow_all will be created
+ resource "aws_vpc_security_group_egress_rule" "allow_all" {
      + arn                    = (known after apply)
      + cidr_ipv4              = "0.0.0.0/0"
      + id                     = (known after apply)
      + ip_protocol            = "-1"
      + security_group_id      = (known after apply)
      + security_group_rule_id = (known after apply)
      + tags_all               = {}
    }

  # module.ec2_bastion.aws_vpc_security_group_ingress_rule.allow_9080 will be created
+ resource "aws_vpc_security_group_ingress_rule" "allow_9080" {
      + arn                    = (known after apply)
      + cidr_ipv4              = "0.0.0.0/0"
      + from_port              = 9080
      + id                     = (known after apply)
      + ip_protocol            = "tcp"
      + security_group_id      = (known after apply)
      + security_group_rule_id = (known after apply)
      + tags_all               = {}
      + to_port                = 9080
    }

  # module.ec2_bastion.aws_vpc_security_group_ingress_rule.allow_ssh will be created
+ resource "aws_vpc_security_group_ingress_rule" "allow_ssh" {
      + arn                    = (known after apply)
      + cidr_ipv4              = "0.0.0.0/0"
      + from_port              = 22
      + id                     = (known after apply)
      + ip_protocol            = "tcp"
      + security_group_id      = (known after apply)
      + security_group_rule_id = (known after apply)
      + tags_all               = {}
      + to_port                = 22
    }

Plan: 8 to add, 0 to change, 2 to destroy.

Changes to Outputs:
~ ec2_atlantis_ip = "3.35.231.83" -> (known after apply)

2024-12-19T09:05:41Z INFO Autodetected 1 Terraform plan binary file project across 1 root module
2024-12-19T09:05:41Z INFO Found Terraform plan binary file project "-home-atlantis-.atlantis-repos-YoonDongGwan-terraform-demo-3-default-aws-default.tfplan" at directory "/home/atlantis/.atlantis/repos/YoonDongGwan/terraform-demo/3/default/aws/default.tfplan"

##### Infracost estimate #####

Monthly cost will increase by $9.60 (+11%%)

Previous monthly cost: $83.77
New monthly cost: $93.37

Infracost output:

    Key: * usage cost, ~ changed, + added, - removed
    
    ──────────────────────────────────
    Project: YoonDongGwan/terraform-demo/aws/default.tfplan
    
    + module.ec2_bastion.aws_instance.ec2_instance
      +$11
    
        + Instance usage (Linux/UNIX, on-demand, t2.micro)
          +$11
    
        + root_block_device
        
            + Storage (general purpose SSD, gp2)
              +$0.91
    
    ~ module.ec2_atlantis.aws_instance.ec2_instance
      -$2 ($41 → $39)
    
        ~ root_block_device
        
            ~ Storage (general purpose SSD, gp3 → gp2)
              -$2 ($3 → $0.91)
    
    Monthly cost change for YoonDongGwan/terraform-demo/aws/default.tfplan
    Amount:  +$10 ($84 → $93)
    Percent: +11%
    
    ──────────────────────────────────
    Key: * usage cost, ~ changed, + added, - removed
    
    *Usage costs can be estimated by updating Infracost Cloud settings, see docs for other options.
    
    29 cloud resources were detected:
    ∙ 4 were estimated
    ∙ 25 were free
    
    Infracost estimate: Monthly estimate increased by $10 ↑
    ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┓
    ┃ Changed project                                    ┃ Baseline cost ┃ Usage cost* ┃ Total change ┃
    ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━╋━━━━━━━━━━━━━━┫
    ┃ YoonDongGwan/terraform-demo/aws/default.tfplan     ┃          +$10 ┃           - ┃  +$10 (+11%) ┃
    ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━━━┻━━━━━━━━━━━━━┻━━━━━━━━━━━━━━┛
```
</details>

* :arrow_forward: To **apply** this plan, comment:
  ```shell
  atlantis apply -d aws
  ```
* :put_litter_in_its_place: To **delete** this plan and lock, click [here](http://a6450007c906:4141/lock?id=YoonDongGwan%252Fterraform-demo%252Faws%252Fdefault)
* :repeat: To **plan** this project again, comment:
  ```shell
  atlantis plan -d aws
  ```
Plan: 8 to add, 0 to change, 2 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this Pull Request, comment:
  ```shell
  atlantis apply
  ```
* :put_litter_in_its_place: To **delete** all plans and locks from this Pull Request, comment:
  ```shell
  atlantis unlock
  ```

**Pull request closed without merging**
